### ISSUE TITLE
[IMPROVEMENT] Update pytest config and related doc

### ISSUE THREAD

**Issue by LuckyPigeon** [rmax/scrapy-redis#212]
## Description

`py.test` has already changed to `pytest` and remove `ignore` keyword from library. Please remove `ignore` section from `pytest.ini` and update related document from `py.test` to `pytest`

## Reproduce the message

Enter following code

```bash
> pytest
```

## Log

![image](https://user-images.githubusercontent.com/32315294/148110623-fc799115-80b8-49d4-9559-ef1e8aa12d54.png)

## Tasks

- [ ] Remove `ignore` section from `pytest.ini`
- [ ] Update text from `py.test` to `pytest` in `CONTRIBUTING.rst`
- [ ] Update text from `py.test` to `pytest` in `Makefile`
- [ ] Update text from `py.test` to `pytest` in `tox.ini`

**Remember following the guide in `CONTRIBUTING.rst` to build your virtual environment and test before sending a PR.**

**Comment by sumit-158** [comment]
can I work on this?

**Comment by LuckyPigeon** [comment]
@sumit-158 
Sure! Please go ahead!
