### ISSUE TITLE
Update basic settings

### ISSUE THREAD

**Issue by LuckyPigeon** [rmax/scrapy-redis#226]
## Description
Our basic settings like `pytest`, `tox.ini`, `LICENSE`... etc, are overtime. Need some update

## Why we need this
Before we have another new release, we need to update our basic settings, include buildings and testing (`CI`/`CD`), and make developers have a better experience.

## Tasks
- [x] LICENSE
- [x] gitignore
- [x] setup.py
- [x] requirements.txt (unify)
- [x] pytest
- [x] tox.ini
- [ ] codecov
- [ ] Wheel
- [ ] Windows build
- [ ] Linux build
- [ ] MacOS build
- [ ] ci
- [ ] CONTRIBUTING.rst
- [ ] All-Contributors bot
- [ ] ISSUE TEMPLATE
- [ ] PULL REQUEST TEMPLATE
